spring.application.name=backend

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.config.import=optional:secrets.properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.datasource.url=jdbc:mysql://localhost:3306/nkm_data

spring.datasource.username=root
spring.datasource.password=secret
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
